<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>cmc</string>
		</array>
		<key>firstLineMatch</key>
		<string></string>
		<key>name</key>
		<string>Cobalt Microcode</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>;.*$</string>
				<key>name</key>
				<string>comment.line</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(revision)\s(\d+)</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.cmc</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.cmc</string>
					</dict>
				</dict>
				<key>name</key>
				<string>keyword.control.directive</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(\d{2})(\s\d{4})(\s[a-zA-Z0-9_]*)(\sBA)?(\s(REG|IMM8|IMM16|(BYTE|WORD)\[SEG\:REG(\+sIMM)?\]|\[SEG\:uIMM16\]))?(\s(REG|IMM8|IMM16|(BYTE|WORD)\[SEG\:REG(\+sIMM)?\]|\[SEG\:uIMM16\]))?(.*((\-|\+)(ZF|CF|SF)|\*))?$</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.cmc</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.cmc</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.cmc</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>storage.type.cmc</string>
					</dict>
					<key>5</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.cmc</string>
					</dict>
					<key>9</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.cmc</string>
					</dict>
					<key>13</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.cmc</string>
					</dict>
				</dict>
			</dict>
			<dict>
				<key>match</key>
				<string>(\#)\s([A-Za-z0-9]+)</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.directive.cmc</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.cmc</string>
					</dict>
				</dict>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)\b(END)\b</string>
				<key>name</key>
				<string>entity.name.function.cmc</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)\b(R|W|BYTE|WORD|ORW1|ORW2)\b</string>
				<key>name</key>
				<string>storage.type.cmc</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)(CS|DS|SS|SEG1|SEG2|\:|(\$[A-Za-z0-9_]*))</string>
				<key>name</key>
				<string>constant.numeric.cmc</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)\b(IPC1|IPC2|IPC4|IPCORW1|IPCORW2|JMP|RTN|JNF)\b</string>
				<key>name</key>
				<string>string.quoted.cmc</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)\b(ADD|SUB|OR|XOR|AND|SHL|SHR)\b</string>
				<key>name</key>
				<string>entity.name.function.cmc</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\#[A-Za-z0-9]*</string>
				<key>name</key>
				<string>keyword.control.directive</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>source.cmc</string>
		<key>uuid</key>
		<string>354efb9a-e590-48c0-a61c-9686c0a9d9cf</string>
	</dict>
</plist>
